### ISSUE TITLE
NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by anoo2niem** [Materialious/Materialious#355]
Hi,

First of all, thank u for this project, it looks very nice.
I ran into an issue while setting it up, this is probably something on my end, but i can't figure out what could be the problem...

I have invidious running on an lxc container on proxmox.

This is my caddyfile; 

```
http://invidious.home {
        @cors_preflight {
                method OPTIONS
        }
        respond @cors_preflight 204

        header Access-Control-Allow-Credentials true
        header Access-Control-Allow-Origin "http://materialious.home/" {
                defer
        }
        header Access-Control-Allow-Methods "GET,POST,OPTIONS,HEAD,PATCH,PUT,DELETE"
        header Access-Control-Allow-Headers "User-Agent,Authorization,Content-Type"

        reverse_proxy localhost:3000
}

http://materialious.home {
   reverse_proxy localhost:3001
}
```

On my config.yml file i have;
`domain: invidious.home`
`external_port: 80`

This is my docker-compose.yml file;

```
version: "3"
services:
  materialious:
    image: wardpearce/materialious:latest
    restart: unless-stopped
    ports:
      - 3001:80
    environment:
      # No trailing backslashes!
      # URL to your proxied Invidious instance
      VITE_DEFAULT_INVIDIOUS_INSTANCE: "http://invidious.home"

      # URL TO RYD
      # Leave blank to disable completely.
      VITE_DEFAULT_RETURNYTDISLIKES_INSTANCE: "https://returnyoutubedislikeapi.com"
  
      # URL to Sponsorblock
      # Leave blank to completely disable sponsorblock.
      VITE_DEFAULT_SPONSERBLOCK_INSTANCE: "https://sponsor.ajay.app"

      # URL to DeArrow
      VITE_DEFAULT_DEARROW_INSTANCE: "https://sponsor.ajay.app"

      # URL to DeArrow thumbnail instance
      VITE_DEFAULT_DEARROW_THUMBNAIL_INSTANCE: "https://dearrow-thumb.ajay.app"

      # Look at "Overwriting Materialious defaults" for all the accepted values.
      VITE_DEFAULT_SETTINGS: '{"themeColor": "#2596be"}'
```

The frontend of materialious is loading, but i got `NetworkError when attempting to fetch resource.` on librewolf and `Failed to fetch` on brave.

Any help would be much apreciated!
