### ISSUE TITLE
CORS issue with Nginx Proxy Manager

### ISSUE THREAD

**Issue by GarandPLG** [Materialious/Materialious#418]
**Describe the bug**
Despite adding the appropriate code to the Advanced section in Nginx Proxy Manager, the Invidious API still does not have the appropriate header allowing Materialious to CORS.

**To Reproduce**
- Setting Nginx Proxy Manager and Cloudflare subdomains for invidious and materialious.
- Adding the appropriate code for Invidious in the Advanced section according to the documentation (with changing example.com to my domain):
```
    if ($request_method = OPTIONS) {
      return 204;
    }

    proxy_hide_header Access-Control-Allow-Origin;
    add_header Access-Control-Allow-Credentials true;
    add_header Access-Control-Allow-Origin "https://materialious.garandplg.com" always;
    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, HEAD, PATCH, PUT, DELETE" always;
    add_header Access-Control-Allow-Headers "User-Agent, Authorization, Content-Type" always;

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
```

**Expected behavior**
For it to work properly, i.e. for Invidious to have the appropriate CORS header

**Desktop:**
 - OS: Ubuntu 24.04 LTS x86_64 (plus docker)
 - Browser: Librewolf

**Additional context**
- Console in materialious returns these error messages:
```
Request to a third-party resource blocked: Same Origin Policy does not allow loading remote resources from "https://invidious.garandplg.com/api/v1/popular" (missing CORS header "Access-Control-Allow-Origin") . Status code: 200.

SyntaxError: JSON.parse: expected double-quoted property name at line 1 column 497 of the JSON data
    Immutable 12
        jh
        x1
        z
        N
        et
        J
        lt
        tt
        Y
        et
        Wt
        nn
    <anonymous> https://materialious.garandplg.com/ line 1 > injectedScript:13
    promise callback* https://materialious.garandplg.com/ line 1 > injectedScript:12
    activateScript https://materialious.garandplg.com/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    n https://materialious.garandplg.com/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    run https://materialious.garandplg.com/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    x https://materialious.garandplg.com/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    runOnLoad https://materialious.garandplg.com/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    runOnLoad https://materialious.garandplg.com/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    x https://materialious.garandplg.com/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    <anonymous> https://materialious.garandplg.com/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    <anonymous> https://materialious.garandplg.com/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    <anonymous> https://materialious.garandplg.com/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
[2.6mbN3oGm.js:2:20681](https://materialious.garandplg.com/_app/immutable/nodes/2.6mbN3oGm.js)
```
- My docker-compose.yml looks like this:
```
services:
  invidious:
    image: quay.io/invidious/invidious:latest
    restart: unless-stopped
    ports:
      - "3066:3000"
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        external_port: 443
        domain: invidious.garandplg.com
        https_only: true
        statistics_enabled: true
        hmac_key: "----------------------------"
        admins: ["--------------------------"]
        use_pubsub_feeds: true
        use_innertube_for_captions: true
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

  materialious:
    image: wardpearce/materialious:latest
    restart: unless-stopped
    ports:
      - 3067:80
    environment:
      VITE_DEFAULT_INVIDIOUS_INSTANCE: "https://invidious.garandplg.com"
      VITE_DEFAULT_RETURNYTDISLIKES_INSTANCE: "https://returnyoutubedislikeapi.com"
      VITE_DEFAULT_SPONSERBLOCK_INSTANCE: "https://sponsor.ajay.app"
      VITE_DEFAULT_DEARROW_INSTANCE: "https://sponsor.ajay.app"
      VITE_DEFAULT_DEARROW_THUMBNAIL_INSTANCE: "https://dearrow-thumb.ajay.app"
      VITE_DEFAULT_SYNCIOUS_INSTANCE: "https://syncious.garandplg.com"
      VITE_DEFAULT_PEERJS_HOST: "peerjs.garandplg.com"
      VITE_DEFAULT_PEERJS_PATH: "/"
      VITE_DEFAULT_PEERJS_PORT: 443
      VITE_DEFAULT_SETTINGS: '{"themeColor": "#d1cf22", "darkMode": true, "region": "PL", "autoPlay": false, "alwaysLoop": false, "proxyVideos": true, "listenByDefault": false, "savePlaybackPosition": true, "dashEnabled": true, "theatreModeByDefault": true, "autoplayNextByDefault": false, "returnYtDislikes": true, "searchSuggestions": true, "previewVideoOnHover": true, "sponsorBlock": true, "sponsorBlockCategories": "sponsor,interaction,selfpromo,intro", "deArrowEnabled": true, "playerMiniPlayer": true, "syncious": true,}'

  api_extended:
    image: wardpearce/invidious_api_extended:latest
    restart: unless-stopped
    ports:
      - 3068:80
    environment:
      api_extended_postgre: '{"host": "invidious-db", "port": 5432, "database": "invidious", "user": "kemal", "password": "kemal"}'
      api_extended_allowed_origins: '["https://materialious.garandplg.com"]'
      api_extended_debug: false

      api_extended_invidious_instance: "https://invidious.garandplg.com"
      api_extended_production_instance: "https://syncious.garandplg.com"

  peerjs-server:
    image: peerjs/peerjs-server
    ports:
      - "3069:9000"
    restart: unless-stopped

volumes:
  postgresdata:
```
- Also a curl response:
```
curl -I https://invidious.garandplg.com/api/v1/popular
HTTP/2 200
date: Mon, 29 Jul 2024 11:58:35 GMT
content-type: text/html
x-frame-options: sameorigin
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
content-security-policy: default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self'; manifest-src 'self'; media-src 'self' blob: https://*.googlevideo.com:443 https://*.youtube.com:443; child-src 'self' blob:; frame-src 'self'; frame-ancestors 'none'
referrer-policy: same-origin
permissions-policy: interest-cohort=()
strict-transport-security: max-age=31536000; includeSubDomains; preload
strict-transport-security: max-age=63072000;includeSubDomains; preload
x-served-by: invidious.garandplg.com
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=D%2BIqISVH2aS%2FX5MiAmynjx5pecA4Ukrs%2B35XImQoxlwWOVM9gmp89SPeW7BG6akQd6K%2Fzo0lCz5HgC41dRb3vK7CHpDxc%2Bkh4%2FSUeLwtM1vgpJVR7dzBtSA95Ck0mb5K%2B8lnrAf1ETnYPw%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 8aacf01d28ebbf18-WAW
alt-svc: h3=":443"; ma=86400
```
